### ISSUE TITLE
WIP and Cycle Time page - The team slicer does not filter correctly.

### ISSUE THREAD

**Issue by MiguelSilva-PBSS** [nbrown02/FlowViz#138]
Hello,

We have a team project with many teams.

On the WIP page, we select/filter a specific team using the "Team" slicer, but the graphs and pop-up show also show data (work items) from other teams.

For example, I selected/filtered the "AA" team, but the "Work item Age" and "Daily Work in Progress (WIP)" charts also show data from the "CC" team.

Wasn't it supposed to only present data from the selected/filtered "AA" team?

Note: The Area Path is common to both teams.

Best regards.

**Desktop (please complete the following information):**
 - power bi desktop
 - Version: FlowViz (Project).pbit - January/2024

**Comment by nbrown02** [comment]
Hey Miguel - thanks for pointing this out. Sounds like a bug, I'll need to triage it and see how I can fix :)

**Comment by MiguelSilva-PBSS** [comment]
I just noticed that this problem also happens on the cycle time page.
Thank you for your attention.

**Comment by nbrown02** [comment]
If an item appears on both teams boards by nature of a shared area path then it should be displayed on cycle time for both teams. So this is the expected behaviour.

**Comment by MiguelSilva-PBSS** [comment]
In Azure Devops, items don't appear on both teams' boards.
Teams can share the same area path, but the iteration path cannot.

In the "Team Configuration" settings in Azure Devops, teams can share the same area path, but have created different iteration paths. Because of this, items do not appear at the same time in both boards.

However, I understood what you said! 

Another problem I found when filtering by team, more specifically in column charts.

The “AA” team created the “Validation” column, but the “CC” team didn't create this column.

The area path is the same for both teams.

On the WIP page, when filtering by "CC" team, in the "Daily Work in Progress (WIP)" graph, the "Validation" column appears, but this team does not have this column on its board!

Thanks.

**Comment by nbrown02** [comment]
Could you send me / email me your setup? I want to try mimic it in a test
area to replicate what you are seeing.

Part of the challenge is I work on this just myself and nowhere near the
scale other orgs will use it!

**Comment by MiguelSilva-PBSS** [comment]
I will share with you the settings I use in the company, so that you can simulate my problems:

Important: All the configurations that I will share are to be done in the same team project!

1- Create two teams:
	1.1 - AA
	1.2 - CC

2. Create the following areas path:
	ABC_Product (parent)
		Sales
			Tables
			Documents
			Settigs
			Reports
		Accounting
			Tables
			Documents
			Settigs
		Purchases
			Tables
			Documents
			Reports
			Settigs

3. Associate ABC_Product with the two teams with the sub-areas included;

4. Create the follwing iterations
	4.1 AA_Iterations (parent)
		Sprint01 (child)
		Sprint02 (child)

	4.2 CC_Iterations (parent)
		Sprint01 (child)
		Sprint02 (child)

5. Associate these iterations with the respective team;
	AA -> AA_Iterations\Sprint01
        AA -> AA_Iterations\Sprint02
	   
   	CC -> CC_Iterations\Sprint01
        CC -> CC_Iterations\Sprint02

7. Configure the following columns on team border:
      7.1 Team AA:
	      New
	      Approved
	      Committed
	      Done
      7.1 Team CC
	      New
	      Approved
	      Committed
	      Validation
	      Done

8. Finally, create the work items with the following characteristics:

      8.1 Team AA:

	      **Work item -** Test AA.1
		      _Area Path:_ ABC_Product
		      _Iteration:_ AA_Iterations\Sprint01
		      _Column Board_: Approved

	      **Work item -** Test AA.2
		      _Area Path:_ ABC_Product\Sales
		      _Iteration:_ AA_Iterations\Sprint01
		      _Column Board:_ Committed
		      
      8.2 Team CC:

	      **Work item -** Test CC.1
		      _Area Path:_ ABC_Product
		      _Iteration:_ CC\Sprint01
		      _Column Board:_ Validation

	      **Work item -** Test CC2
		      _Area Path:_ ABC_Product\Accounting\Documents
		      _Iteration:_ CC_Iterations\Sprint01
		      _Column Board:_ Committed

Thank you for your attention.

**Comment by nbrown02** [comment]
Should now be fixed if you want to give it a retest...

**Comment by MiguelSilva-PBSS** [comment]
I will retest.
I need to download it again, right?

**Comment by nbrown02** [comment]
Yup that’s correct :)Sent from my iPhoneOn 16 Sep 2024, at 18:27, Miguel Silva ***@***.***> wrote:﻿
I will retest.
I need to download it again, right?

**Comment by MiguelSilva-PBSS** [comment]
Hi,

I did some tests on the various pages, but I think the problem is not 100% resolved yet.

On the “WIP” page it is resolved, but on the “Dashboard” and “Cycle Time” pages it isn't resolved.

For example,  
on the "Dashboard" page, if we do "Drill through" (page D1), the work items of the "CC" team will appear in the list, but I only selected the "AA" team. So, I don't know if the error is just in the "D1" tooltip or if the chart is also including data from other teams.
 In the "Quality (bug rate)" chart, the same thing also happens when we do "Drill through" ("page D2").

On the "Cycle time" page, the "Cycle time scatterplot" and "Lead time scatterplot" graphs continue to display work items from other teams when I filter just one team.
Also on this page, the "Avegare Cycle Time per Week by Work Item" chart lists work items from other teams when we "Drill through" ("page D3").

I didn't get to test the "Average Lead Time Per Weel by Work Item" chart.

Thanks for your effort and attention.

**Comment by nbrown02** [comment]
Hmm strange. Is that using the same setup? Just wondering what I can to
mimic it my end...

**Comment by nbrown02** [comment]
Thanks - I am going to take a proper look at it this week to fix :)

**Comment by MiguelSilva-PBSS** [comment]
Hi,

Did you fix the issue?
I'm available to validate again!

**Comment by nbrown02** [comment]
Unfortunately not, time got away from me this week. I will have time on
Monday!

**Comment by nbrown02** [comment]
This is fixed now :)

**Comment by MiguelSilva-PBSS** [comment]
Hello,

I confirm that on the "Cycle Time" page the issue is resolved.

However, the problem continues on the "Dashboard" page.
As I mentioned before, on this page if we do "Drill through" (page D1), the work items of the "CC" team will appear in the list, but I only selected the "AA" team. So, I don't know if the error is just in the "D1" tooltip or if the chart is also including data from other teams.
In the "Quality (bug rate)" chart, the same thing also happens when we do "Drill through" ("page D2").


Would you prefer I create a new issue referenced only on this page?

**Comment by nbrown02** [comment]
@MiguelSilva-PBSS - try the latest version (just published another one) and see if still exists then please open a new issue if it does :)

**Comment by MiguelSilva-PBSS** [comment]
This issue was resolved, but unfortunately another one appeared.

When I filter a team, bugs are not considered, but only when a team has the "bugs are managed with tasks" configuration.
I will create a new issue, with more details so you can simulate it.

Thanks.

**Comment by nbrown02** [comment]
As per #139 - no plans to fix this due to effort vs. value a fix would bring.
